@startuml Biblioteca Pessoal Sequencia Seguir Autor
package "Usuários" {
    object Leitor
}

package "Sistemas Internos" {
    object FrontExibirAutor
    object "SA : Autor" as Autor
    object DataBase
}


Leitor --> FrontExibirAutor : 1.1 exibirAutor(autorId)
Leitor --> FrontExibirAutor : 2.1 seguirAutor(autorId, leitorId)
FrontExibirAutor --> Autor : 1.2 exibirAutor(autorId)
FrontExibirAutor --> Autor : 2.2 seguirAutor(autorId, leitorId)
Autor --> DataBase : 1.3 getLeitorById(autorId)
Autor --> DataBase : 2.3 addSeguidor(autorId, leitorId)
DataBase --> Autor : 1.4 autor
DataBase --> Autor
Autor --> FrontExibirAutor : 1.5 autor
@enduml