@startuml Biblioteca Pessoal Sequencia Notifição
    actor autor
    boundary FrontCriarLivro
    control "AS : Autor" as Autor
    database DataBase
    actor notificador

    == Criar Livro ==
    autor -> FrontCriarLivro : criarLivro(dados)
    FrontCriarLivro -> Autor : createLivro(dados)
    Autor -> DataBase : createLivro(dados)
    DataBase --> Autor : leitores seguidores

    == Notificar Seguidores ==
    loop para cada leitor seguidor
        Autor -> notificador : notificar(leitorId)
    end
@enduml
